"""commits table

Revision ID: 53fa07717feb
Revises: 6276c735f430
Create Date: 2020-05-29 21:06:22.422299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53fa07717feb'
down_revision = '6276c735f430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commit_text', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commits_commit_text'), 'commits', ['commit_text'], unique=False)
    op.create_index(op.f('ix_commodities_price'), 'commodities', ['price'], unique=False)
    op.drop_index('ix_orders_email', table_name='orders')
    op.create_index(op.f('ix_orders_email'), 'orders', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_email'), table_name='orders')
    op.create_index('ix_orders_email', 'orders', ['email'], unique=1)
    op.drop_index(op.f('ix_commodities_price'), table_name='commodities')
    op.drop_index(op.f('ix_commits_commit_text'), table_name='commits')
    op.drop_table('commits')
    # ### end Alembic commands ###
