"""orders table

Revision ID: 6276c735f430
Revises: ff03088efe6f
Create Date: 2020-05-17 09:00:06.200787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6276c735f430'
down_revision = 'ff03088efe6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phno', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('orderlist', sa.String(length=200), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_address'), 'orders', ['address'], unique=False)
    op.create_index(op.f('ix_orders_area'), 'orders', ['area'], unique=False)
    op.create_index(op.f('ix_orders_email'), 'orders', ['email'], unique=True)
    op.create_index(op.f('ix_orders_order_date'), 'orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_orders_orderlist'), 'orders', ['orderlist'], unique=False)
    op.create_index(op.f('ix_orders_username'), 'orders', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_username'), table_name='orders')
    op.drop_index(op.f('ix_orders_orderlist'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_date'), table_name='orders')
    op.drop_index(op.f('ix_orders_email'), table_name='orders')
    op.drop_index(op.f('ix_orders_area'), table_name='orders')
    op.drop_index(op.f('ix_orders_address'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
