"""add databases

Revision ID: ff03088efe6f
Revises: 
Create Date: 2020-05-16 08:20:37.531654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff03088efe6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemname', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commodities_itemname'), 'commodities', ['itemname'], unique=True)
    op.create_index(op.f('ix_commodities_quantity'), 'commodities', ['quantity'], unique=False)
    op.create_table('gov_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gov_db_email'), 'gov_db', ['email'], unique=True)
    op.create_index(op.f('ix_gov_db_username'), 'gov_db', ['username'], unique=True)
    op.create_table('seller_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('area', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_db_area'), 'seller_db', ['area'], unique=True)
    op.create_index(op.f('ix_seller_db_email'), 'seller_db', ['email'], unique=True)
    op.create_index(op.f('ix_seller_db_username'), 'seller_db', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seller_db_username'), table_name='seller_db')
    op.drop_index(op.f('ix_seller_db_email'), table_name='seller_db')
    op.drop_index(op.f('ix_seller_db_area'), table_name='seller_db')
    op.drop_table('seller_db')
    op.drop_index(op.f('ix_gov_db_username'), table_name='gov_db')
    op.drop_index(op.f('ix_gov_db_email'), table_name='gov_db')
    op.drop_table('gov_db')
    op.drop_index(op.f('ix_commodities_quantity'), table_name='commodities')
    op.drop_index(op.f('ix_commodities_itemname'), table_name='commodities')
    op.drop_table('commodities')
    # ### end Alembic commands ###
